formatter: markdown table

header-from: main.tf
footer-from: "docs/.footer.md"

recursive:
  enabled: true

sections:
  hide:
    - providers

output:
  file: "README.md"
  mode: replace
  # template: |-
  #   <!-- BEGIN_TF_DOCS -->
  #   {{ .Content }}
  #   <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

content: |-
  {{ .Header }}

  ## Example

  ```hcl
  {{ include "examples/shared/main.tf" }}
  ```

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Footer }}
