apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ext-namespace-metadata-linkerd-config
  namespace: linkerd
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["linkerd-config"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ext-namespace-metadata-linkerd-config
  namespace: linkerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ext-namespace-metadata-linkerd-config
subjects:
- kind: ServiceAccount
  name: namespace-metadata
  namespace: linkerd-viz