name: format
on:
  pull_request:
  workflow_dispatch:
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - uses: actions/checkout@v2
      with:
        ref: refs/heads/${{ github.head_ref }}
    - uses: hashicorp/setup-terraform@v1
    # Run Terraform format
    - name: format / terraform
      id: fmt
      run: terraform fmt -recursive
      continue-on-error: true
    # Run Go fmt
    - name: format / go
      run: go fmt ./test
    # Run Prettier
    - name: format / prettier
      uses: creyD/prettier_action@v3.3
      with:
        prettier_options: --write **/*.{json,yaml}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Commit changes
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        git push